version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_NAME: django
      DB_USER: admin
      DB_PASSWORD: admin
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:5000"]

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null
